spring.application.name=pms-app

spring.datasource.url=jdbc:postgresql://localhost:5432/pms
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#jwt.secret=${JWT_SECRET:hjshgghuheurwiesujxkklk.mvkncvnxkvdukjzfskfnjnkjsdfkjsdkhgkjdshgkjhghdkjgkjijgiewiurifjsdf}
#jwt.issuer=${JWT_ISSUER:hrms-pms-app}
#jwt.expiration=${JWT_EXPIRATION:3600}
#jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}
#
#jwt.refresh-cookie-name=${JWT_REFRESH_COOKIE_NAME:refreshToken}
#jwt.cookie-secure=${JWT_COOKIE_SECURE:true}
#jwt.cookie-http-only=${JWT_COOKIE_HTTP_ONLY:true}
#jwt.cookie-same-site=${JWT_COOKIE_SAME_SITE:lax}

jwt.secret=${JWT_SECRET:hjshgghuheurwiesujxkklk.mvkncvnxkvdukjzfskfnjnkjsdfkjsdkhgkjdshgkjhghdkjgkjijgiewiurifjsdf}
jwt.issuer=${JWT_ISSUER:hrms-pms-app}
jwt.expiration=3600
jwt.refresh-expiration=604800

jwt.refresh-cookie-name=${JWT_REFRESH_COOKIE_NAME:refreshToken}
jwt.cookie-secure=${JWT_COOKIE_SECURE:true}
jwt.cookie-http-only=${JWT_COOKIE_HTTP_ONLY:true}
jwt.cookie-same-site=${JWT_COOKIE_SAME_SITE:none}
jwt.cookie-domain=${JWT_COOKIE_DOMAIN:}
